### ISSUE TITLE
Hebrew in [NativeLanguageNames] is reversed

### ISSUE THREAD

**Issue by snil4** [Tiny-Foxes/OutFox-Translations#4]
A really small thing that's bugging me is how the translation for hebrew is showen in-game reversed in the language selection option (or any other Right-to-Left language including arabic and more). The simple solution is to just reverse the text in [NativeLanguageNames].
How it looks now in most files: עברית
How it should look in all files: תירבע
I hope it's not too much to ask but it's better to deal with it now then later when more languages add up.

**Comment by moruzerinho6** [comment]
Fixed in 217e73a
